### PR TITLE
Remove hadoop-common dependency

### PR DESCRIPTION
**Pull request by stuarthendren**
There are only a couple of methods used so replicated and removed the dependency. 
hadoop-common is a large dependency which pulls in a lot of other dependencies these (such as javax.servlet) can cause version issue when using the library.

### CODE REVIEW

**Review by thomasjungblut — APPROVED** [review]
Thanks for cleaning this up. Looks good from glossing over.

Do you need a new release in maven central?

**Comment by stuarthendren** [comment]
If you have the time, that would be great.

**Comment by thomasjungblut** [comment]
sure, no worries- let me just run the release.

**Comment by thomasjungblut** [comment]
@stuarthendren just released as 0.3. Give it a couple of hours until it shows up, if it doesn't just let me know.

**Pull request merged**
